<?php

namespace Database\Seeders;

use App\Models\Province;
use App\Models\Department;
use App\Models\Locality;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $sj = Province::firstOrCreate(['name' => 'San Juan']);

        $data = [
            '25 De Mayo' => [
                '25 De Mayo',
                'Campos De Aibilí',
                'Cuatro Esquinas',
                'Divisoria',
                'Encon',
                'La Chimbera',
                'Las Casuarinas',
                'Las Trancas',
                'Pozo Salado',
                'Punta Del Agua',
                'Santa Rosa',
                'Tupelí',
                'Villa Santa Rosa',
            ],
            '9 De Julio' => [
                'La Majadita',
                'Las Chacritas',
                'Rincon Cercado',
                'Villa 9 De Julio',
                'Villa Cabecera',
            ],
            'Albardon' => [
                'Albardon',
                'Campo Afuera',
                'El Topon',
                'La Cañada',
                'Las Lomitas',
                'Las Piedritas',
                'Las Tapias',
                'Las Tierritas',
                'Obispo Zapata',
                'Villa General San Martín',
                'Villa San Martin',
                'Villa San Miguel',
            ],
            'Angaco' => [
                'El Alamito',
                'El Bosque',
                'La Cañada',
                'Las Tapias',
                'Plumerillo',
                'Punta Del Monte',
                'Villa Del Salvador',
                'Villa El Salvador',
            ],
            'Calingasta' => [
                'Alcaparrosa',
                'Alto Calingasta',
                'Barreal',
                'Calingasta',
                'Colon',
                'Hilario',
                'La Isla',
                'Las Hornillas',
                'Puchuzum',
                'Sorocayense',
                'Tamberias',
                'Villa Calingasta',
                'Villa Corral',
                'Villa Nueva',
            ],
            'Capital' => [
                'B° Cabot',
                'B° Frondizi',
                'B° S.M.A.T.A.',
                'Capital',
                'Chimbas',
                'Concepción',
                'Desamparados',
                'Trinidad',
                'Trinidad (Cap)',
                'Villa Del Carril',
            ],
            'Caucete' => [
                'Bº Bermejo',
                'Casas Viejas',
                'Caucete',
                'Divisoria',
                'El Rincón',
                'La Planta',
                'La Puntilla',
                'Laguna Seca Bermejo',
                'Las Chacras',
                'Las Liebres',
                'Los Medanos',
                'Lotes De Alvarez',
                'Marayes',
                'Pie De Palo',
                'Pozo De Los Algarrobos',
                'Vallecito - Paraje Difunta Correa',
            ],
            'Chimbas' => [
                'B° Andacollo',
                'B° Centenario',
                'B° Guemes',
                'B° Laprida',
                'B° Los Alerces',
                'B° Los Andes',
                'B° Los Tamarindo',
                'B° Parque Independencia',
                'B° Parque Industrial',
                'B° Santa Maria Conjunto 3',
                'Bº Chimbas Ii',
                'Bº Los Pinos',
                'Bº Los Tamarindo',
                'Bº Norte',
                'Chimbas',
                'Chimbas Norte',
                'El Mogote',
                'Villa Del Salvador',
                'Villa Maria',
                'Villa Mariano Moreno',
                'Villa Morrone',
                'Villa Obrera',
                'Villa Observatorio',
                'Villa Paula',
                'Villa Sarmiento',
                'Villa Union',
            ],
            'Iglesia' => [
                'Angualasto',
                'Bauchaceta',
                'Bella Vista',
                'Colanguil',
                'Colola',
                'Las Flores',
                'Maliman',
                'Pismanta',
                'Rodeo',
                'Tudcum',
                'Villa Iglesia',
                'Zonda',
            ],
            'Jáchal' => [
                'Alto Huaco',
                'Bella Vista',
                'Boca De La Quebrada',
                'B° San Jose',
                'Bº Fronteras Argentinas',
                'El Bajo Huaco',
                'El Fical',
                'El Medano',
                'El Rincón',
                'El Volcán',
                'Huaco',
                'Huerta De Huachi',
                'La Cienega',
                'La Falda',
                'La Frontera',
                'La Represa',
                'Los Puestos',
                'Mogna',
                'Niquivil',
                'Pachimoco',
                'Pampa Del Chañar',
                'Pampa Vieja',
                'Puesto Chepical',
                'San Isidro',
                'San Jose De Jachal',
                'San Roque',
                'Tamberias',
                'Villa Mercedes',
            ],
            'Pocito' => [
                'Campo De Batalla',
                'Carpinteria',
                'Colonia Rodas',
                'Cuarto Cartel',
                'La Callecita',
                'La Rinconada',
                'Pocito',
                'Pocito Norte',
                'Quinto Cuartel',
                'Rinconada',
                'Segundo Cuartel',
                'Villa Aberastain',
                'Villa Aberastain (Poc)',
                'Villa Aeroparque',
                'Villa Paolini',
            ],
            'Rawson' => [
                'B° 12 De Diciembre',
                'B° 24 De Noviembre',
                'B° Buenaventura Luna',
                'B° Capitan Lazo',
                'B° Edilco',
                'B° Franklin Rawson',
                'B° Guemes',
                'B° Hualilan',
                'B° Hugo Montaño',
                'B° Monseñor Orzali',
                'B° Residencial',
                'B° Residencial Obrero',
                'B° S. M. Del Carril',
                'B° San Ricardo',
                'Bº Borges',
                'Bº La Estación',
                'Bº Sierras Moradas',
                'Bº Valle Grande',
                'Capitan Lazo',
                'Colonia Rodas',
                'Los Corredores',
                'Medanito',
                'Medano De Oro',
                'Rawson',
                'Villa Krause',
                'Villa San Damian',
                'Vº Bolaños',
                'Vº Hipodromo',
            ],
            'Rivadavia' => [
                'B° Aramburu',
                'B° Camus',
                'B° Fortabat',
                'B° Hauzihul',
                'B° Huaziul',
                'B° Jardin Policial',
                'B° Marquesado',
                'B° Nueva Argentina',
                'B° Parque Rivadavia Norte',
                'B° Piuquen',
                'B° Rivadavia Sur',
                'B° Udap Iii',
                'Bº Camus',
                'Bº Fortabat',
                'Bº Natania Xv',
                'Bº San Juan',
                'Hospital Marcial Quiroga',
                'La Bebida',
                'Marquesado',
                'Marquezado',
                'Rivadavia',
                'Villa San Francisco',
            ],
            'San Martín' => [
                'Dos Acequias',
                'La Punilla',
                'La Puntilla',
                'Los Compartos',
                'San Isidro',
                'Villa Alem',
                'Villa Dominguito',
                'Villa Lugano',
            ],
            'Santa Lucía' => [
                'Alto De Sierra',
                'Barrio Kennedy',
                'Bermejito',
                'B° Balcarce',
                'Colonia Gutierrez',
                'Colonia Richet Zapata',
                'Esquina Del Sauce',
                'La Legua',
                'Las Piedritas',
                'Santa Lucia',
                'Villa Maria',
            ],
            'Sarmiento' => [
                'Campo Vid',
                'Cañada Honda',
                'Cieneguita',
                'Cochagual',
                'Colonia Fiscal',
                'Divisadero',
                'Huanacache',
                'Las Lagunas',
                'Los Berros',
                'Mediagua',
                'Pedernal',
                'Retamito',
                'San Carlos',
                'Tres Esquinas',
                'V° Media Agua',
            ],
            'Ullum' => [
                'Ullum',
                'Villa Aurora',
                'Villa Ibañez',
            ],
            'Valle Fértil' => [
                'Agua Cercada',
                'Astica',
                'Bajo Chucuma',
                'Baldes De Astica',
                'Baldes De Fune',
                'Baldes De Las Chilcas',
                'Baldes De Rosario',
                'Baldes Del Norte',
                'Baldes Del Sur',
                'Chucuma',
                'Colonia Los Valecianos',
                'La Majadita',
                'Las Juntas',
                'Los Baldecitos',
                'Los Bretes',
                'Sierras De Chavez',
                'Sierras De Elizondo',
                'Usno',
                'Villa San Agustin',
            ],
            'Zonda' => [
                'V° Basilio Nievas',
                'Zonda',
            ],
        ];

        foreach ($data as $deptName => $localities) {
            $dept = Department::updateOrCreate(
                ['province_id' => $sj->id, 'name' => $deptName]
            );

            foreach ($localities as $locName) {
                Locality::updateOrCreate(
                    ['department_id' => $dept->id, 'name' => $locName]
                );
            }
        }
    }
}
